services:
  - type: web
    name: synergysquad-live-quiz
    runtime: node
    buildCommand: "cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install"
    startCommand: "cd backend && node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
